/*! \file api.h
  \brief Main API header, that includes the others.

  This should be the only header file included by applications.  It
  should allow for general I/O functions, but nothing internal to a
  driver.  (But of course it includes too much for now.)
*/

#include <stdint.h>
#include <msp430.h>

#include "config.h"
#include "configdefault.h"

//GoodWatch modules.
#include "lcd.h"
#include "uart.h"
#include "monitor.h"
#include "ucs.h"
#include "lcdtext.h"
#include "keypad.h"
#include "apps.h"
#include "rtc.h"
#include "sidebutton.h"
#include "radio.h"
#include "packet.h"
#include "codeplug.h"
#include "power.h"
#include "dmesg.h"
#include "gittag.h" //Autogenerated

//Handy libraries.  These are tested host-side.
#include "libs/assembler.h"
#include "libs/morse.h"

//Standalone functions.

typedef struct post_status {
  uint8_t failed: 1;  // Have any tests failed?
  uint8_t lcd_bad: 1;
  uint8_t crystal_bad: 1;
  uint8_t rf_low_vcore: 1;
  uint8_t rf_operand_err: 1;
  uint8_t rf_out_data_err: 1;
  uint8_t rf_operand_overrite_err: 1;
} post_status;

//! Power On Self Test
post_status post();

void display_post(post_status status);
